# Generated by Django 5.0.5 on 2024-05-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_data',
            new_name='ordered_date',
        ),
    ]
