# Generated by Django 5.0.5 on 2024-06-23 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeAdmin', '0002_rename_name_cafe_cafe_name'),
        ('core', '0002_alter_menuitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cafe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cafeAdmin.cafe'),
        ),
    ]
