# Generated by Django 5.0.5 on 2024-05-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_half_portion',
            field=models.BooleanField(default=False),
        ),
    ]
