# Generated by Django 5.0.5 on 2024-07-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
