# Generated by Django 5.0.5 on 2024-06-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment_payment_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_charge_id',
            field=models.CharField(max_length=50),
        ),
    ]
