# Generated by Django 5.0.5 on 2024-07-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_payment_user_payment_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('razorpay', 'Razorpay')], max_length=50),
        ),
    ]
