# Generated by Django 5.0.5 on 2024-07-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_payment_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_charge_id',
            new_name='razorpay_charge_id',
        ),
    ]
