# Generated by Django 5.0.5 on 2024-06-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='contact_number',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AddField(
            model_name='cafe',
            name='email',
            field=models.EmailField(default=False, max_length=50, unique=True),
        ),
    ]
