# Generated by Django 5.0.5 on 2024-06-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='name',
            new_name='cafe_name',
        ),
    ]
