# Generated by Django 5.0.5 on 2024-06-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeAdmin', '0002_cafe_contact_number_cafe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
