# Generated by Django 5.0.5 on 2024-06-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeAdmin', '0002_rename_name_cafe_cafe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
