# Generated by Django 5.0.5 on 2024-05-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeAdmin', '0002_remove_menuitem_category_alter_menuitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
