# Generated by Django 5.0.5 on 2024-07-09 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeAdmin', '0003_cafe_qr_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
