# Generated by Django 5.0.5 on 2024-06-16 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeAdmin', '0003_alter_cafe_contact_number_alter_cafe_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('cafe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafeAdmin.cafe')),
            ],
        ),
    ]
