# Generated by Django 5.0.5 on 2024-06-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeAdmin', '0004_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='unique_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
