# Generated by Django 5.0.5 on 2024-05-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeAdmin', '0004_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(default='False'),
        ),
    ]
